### PR TITLE
Wildlife practice worlds

### PR DESCRIPTION
**Pull request by caguero**
How to test it?

Start the simulations with:
```
ros2 launch vrx_gz competition.launch.py world:=practice_2022_wildlife0_task
ros2 launch vrx_gz competition.launch.py world:=practice_2022_wildlife1_task
ros2 launch vrx_gz competition.launch.py world:=practice_2022_wildlife2_task
```

Follow the instructions from #547.

### CODE REVIEW

**Comment by M1chaelM** [comment]
@caguero  It looks like collision detection may not be working for some reason. I am able to circumnavigate the animals, but crashing into them doesn't reset progress. Should I create a separate issue for this?

**Comment by caguero** [comment]
> 4ab981e

I think I've restored collisions in [4ab981e](https://github.com/osrf/vrx/pull/585/commits/4ab981ecf26f39a96d4345d8361084fd841e7680) . 

The problem is that there's some URDF->SDF conversion and some links connected with fixed joints are automatically grouped together including its collision geometries. The collision names seem to change when we modify the SDF. This isn't ideal but it should be working for now.

**Comment by caguero** [comment]
@M1chaelM , the environmental conditions have been updated. This PR is ready for review.

**Comment by M1chaelM** [comment]
@caguero It looks like the `/vrx/wildlife/animals/poses` topic is not being bridged to ROS 2. Could you take a look?

**Comment by caguero** [comment]
> @caguero It looks like the `/vrx/wildlife/animals/poses` topic is not being bridged to ROS 2. Could you take a look?

This wasn't a trivial change. The problem is that there's no standard type in Gz and ROS that we can use to send that information over the bridge (an array of animals where each animal is represented by a string type and a pose).

The suboptimal solution that I found was to bridge it with `msgs.Pose_V --> geometry_msgs::msgs::ParamVec`. See it [here](https://github.com/gazebosim/ros_gz/blob/humble/ros_gz_interfaces/msg/ParamVec.msg).

This is how this looks on the ROS 2 side:

```
---
header:
  stamp:
    sec: 87
    nanosec: 932000000
  frame_id: ''
params:
- name: param_0/position_x
  value:
    type: 3
    bool_value: false
    integer_value: 0
    double_value: -33.72270430132833
    string_value: ''
    byte_array_value: []
    bool_array_value: []
    integer_array_value: []
    double_array_value: []
    string_array_value: []
- name: param_0/position_y
  value:
    type: 3
    bool_value: false
    integer_value: 0
    double_value: 150.67377777220986
    string_value: ''
    byte_array_value: []
    bool_array_value: []
    integer_array_value: []
    double_array_value: []
    string_array_value: []
- name: param_0/type
  value:
    type: 4
    bool_value: false
    integer_value: 0
    double_value: 0.0
    string_value: crocodile
    byte_array_value: []
    bool_array_value: []
    integer_array_value: []
    double_array_value: []
    string_array_value: []
- name: param_0/position_z
  value:
    type: 3
    bool_value: false
    integer_value: 0
    double_value: 0.09079390205442905
    string_value: ''
    byte_array_value: []
    bool_array_value: []
    integer_array_value: []
    double_array_value: []
    string_array_value: []
- name: param_0/orientation_w
  value:
    type: 3
    bool_value: false
    integer_value: 0
    double_value: 0.3845808696171916
    string_value: ''
    byte_array_value: []
    bool_array_value: []
    integer_array_value: []
    double_array_value: []
    string_array_value: []
- name: param_0/orientation_x
  value:
    type: 3
    bool_value: false
    integer_value: 0
    double_value: -1.4402471953322843e-11
    string_value: ''
    byte_array_value: []
    bool_array_value: []
    integer_array_value: []
    double_array_value: []
    string_array_value: []
- name: param_0/orientation_y
  value:
    type: 3
    bool_value: false
    integer_value: 0
    double_value: -3.796190318211065e-12
    string_value: ''
    byte_array_value: []
    bool_array_value: []
    integer_array_value: []
    double_array_value: []
    string_array_value: []
- name: param_0/orientation_z
  value:
    type: 3
    bool_value: false
    integer_value: 0
    double_value: 0.9230913035688748
    string_value: ''
    byte_array_value: []
    bool_array_value: []
    integer_array_value: []
    double_array_value: []
    string_array_value: []
- name: param_1/position_x
  value:
    type: 3
    bool_value: false
    integer_value: 0
    double_value: -33.72270274924732
    string_value: ''
    byte_array_value: []
    bool_array_value: []
    integer_array_value: []
    double_array_value: []
    string_array_value: []
- name: param_1/position_y
  value:
    type: 3
    bool_value: false
    integer_value: 0
    double_value: 150.67420845262285
    string_value: ''
    byte_array_value: []
    bool_array_value: []
    integer_array_value: []
    double_array_value: []
    string_array_value: []
- name: param_1/position_z
  value:
    type: 3
    bool_value: false
    integer_value: 0
    double_value: 0.030728192068636417
    string_value: ''
    byte_array_value: []
    bool_array_value: []
    integer_array_value: []
    double_array_value: []
    string_array_value: []
- name: param_1/type
  value:
    type: 4
    bool_value: false
    integer_value: 0
    double_value: 0.0
    string_value: platypus
    byte_array_value: []
    bool_array_value: []
    integer_array_value: []
    double_array_value: []
    string_array_value: []
- name: param_1/orientation_w
  value:
    type: 3
    bool_value: false
    integer_value: 0
    double_value: 0.8450185075012782
    string_value: ''
    byte_array_value: []
    bool_array_value: []
    integer_array_value: []
    double_array_value: []
    string_array_value: []
- name: param_1/orientation_x
  value:
    type: 3
    bool_value: false
    integer_value: 0
    double_value: 0.0012384507856327497
    string_value: ''
    byte_array_value: []
    bool_array_value: []
    integer_array_value: []
    double_array_value: []
    string_array_value: []
- name: param_1/orientation_y
  value:
    type: 3
    bool_value: false
    integer_value: 0
    double_value: 0.0019755915315614837
    string_value: ''
    byte_array_value: []
    bool_array_value: []
    integer_array_value: []
    double_array_value: []
    string_array_value: []
- name: param_1/orientation_z
  value:
    type: 3
    bool_value: false
    integer_value: 0
    double_value: -0.5347319751595787
    string_value: ''
    byte_array_value: []
    bool_array_value: []
    integer_array_value: []
    double_array_value: []
    string_array_value: []
- name: param_2/position_x
  value:
    type: 3
    bool_value: false
    integer_value: 0
    double_value: -33.72269552746456
    string_value: ''
    byte_array_value: []
    bool_array_value: []
    integer_array_value: []
    double_array_value: []
    string_array_value: []
- name: param_2/position_y
  value:
    type: 3
    bool_value: false
    integer_value: 0
    double_value: 150.67463631180422
    string_value: ''
    byte_array_value: []
    bool_array_value: []
    integer_array_value: []
    double_array_value: []
    string_array_value: []
- name: param_2/position_z
  value:
    type: 3
    bool_value: false
    integer_value: 0
    double_value: -1.842435449361801e-05
    string_value: ''
    byte_array_value: []
    bool_array_value: []
    integer_array_value: []
    double_array_value: []
    string_array_value: []
- name: param_2/type
  value:
    type: 4
    bool_value: false
    integer_value: 0
    double_value: 0.0
    string_value: turtle
    byte_array_value: []
    bool_array_value: []
    integer_array_value: []
    double_array_value: []
    string_array_value: []
- name: param_2/orientation_w
  value:
    type: 3
    bool_value: false
    integer_value: 0
    double_value: 0.5264971702853152
    string_value: ''
    byte_array_value: []
    bool_array_value: []
    integer_array_value: []
    double_array_value: []
    string_array_value: []
- name: param_2/orientation_x
  value:
    type: 3
    bool_value: false
    integer_value: 0
    double_value: -0.0014604711846198232
    string_value: ''
    byte_array_value: []
    bool_array_value: []
    integer_array_value: []
    double_array_value: []
    string_array_value: []
- name: param_2/orientation_y
  value:
    type: 3
    bool_value: false
    integer_value: 0
    double_value: 0.0009044418236161299
    string_value: ''
    byte_array_value: []
    bool_array_value: []
    integer_array_value: []
    double_array_value: []
    string_array_value: []
- name: param_2/orientation_z
  value:
    type: 3
    bool_value: false
    integer_value: 0
    double_value: 0.8501751458908114
    string_value: ''
    byte_array_value: []
    bool_array_value: []
    integer_array_value: []
    double_array_value: []
    string_array_value: []
---
```

**Comment by M1chaelM** [comment]
Yikes, OK. I will try to document this. Can't wait for the ability to bridge custom messages!

**Comment by caguero** [comment]
> Is there any way we can set the "name" field of the parameters to something more descriptive than `param_0`, `param_1`, etc.? For example, `turtle/position_x' instead of `param_0/orientation_x'?

We can't unfortunately, that's populated automatically.

**Comment by M1chaelM** [comment]
OK, I think we should go ahead as-is for now and I'll try to describe it. For a future release, what do you think about having a separate topic for each animal? Then we could put the animal name in the topic and just publish the coordinates.

**Comment by caguero** [comment]
> OK, I think we should go ahead as-is for now and I'll try to describe it. For a future release, what do you think about having a separate topic for each animal? Then we could put the animal name in the topic and just publish the coordinates.

I thought about the individual topics and it definitely will simplify the message and the parsing but I thought we wanted to generalize a bit more the task considering a non-fixed number of animals.

**Review by M1chaelM — APPROVED** [review]

**Comment by M1chaelM** [comment]
> I thought about the individual topics and it definitely will simplify the message and the parsing but I thought we wanted to generalize a bit more the task considering a non-fixed number of animals.

I agree we want this, but I think it's still possible to dynamically change the number of topics we're publishing.  In any case it may not be pressing because right now the documentation says there will be 3 animals (but not necessarily that there is always 1 of each).

**Pull request merged**
