### PR TITLE
Toward consistent local (Gazebo) and geographic (GPS) coordinates.

### PR DESCRIPTION
**Pull request by bsb808**
Begins to address Issue #353 .

This PR is on top of PR #354 , so probably best to merge that one first, then rebase before merging.

* Remove the 180 deg rotation of the Sydney Regatta which causes issue #353.
* Modification the model pose values in`sydneyregatta.xacro` so that the models (post, ground stations, etc.) are in the same location relative to the Regatta map.
* Mod. of world file to change camera view
* Mod. of the launch file change WAM-V default initial pose.

I checked the consistency of the Gazebo / Hector GPS coordinates with Google Earth...

sydney_regatta

I have not yet tried the various VRX tasks to see what other local coordinate values need to be modified to maintain the desired relative location of models.

### CODE REVIEW

**Comment by M1chaelM** [comment]
@bsb808 Looking at this now. Since it is on top of #354, why don't we change the merge target to `bsb/use_spherical` so we can test both together before merging either into the master?

**Comment by caguero** [comment]
Consider to look at [this pull request](https://github.com/ignitionrobotics/ign-math/pull/235) in Ignition Math in case we're impacted with the `SphericalCoordinates` fix detailed in that PR.

**Comment by bsb808** [comment]
Also, see https://github.com/osrf/vrx/pull/358 - has additional documentation on this issue.

**Comment by bsb808** [comment]
Closing b/c we are working directly on #354

**Pull request closed without merging**
