### PR TITLE
Updated wind plugin: practice worlds

### PR DESCRIPTION
**Pull request by j-herman**
Updating wind plugin for practice_2022 worlds

### CODE REVIEW

**Comment by j-herman** [comment]
To test each world:
`ros2 launch vrx_gz competition.launch.py world:=practice_2022_<tasknameX>_task`
In another terminal, confirm wind topics are publishing correctly through the ros bridge:
`ros2 topic echo /vrx/debug/wind/direction` or `ros2 topic echo /vrx/debug/wind/speed`

**Comment by M1chaelM** [comment]
Test progress:
* [ ] practice_2022_acoustic_perception0_task.sdf
* [ ] practice_2022_acoustic_perception1_task.sdf
* [ ] practice_2022_acoustic_perception2_task.sdf
* [ ] practice_2022_acoustic_tracking0_task.sdf
* [ ] practice_2022_acoustic_tracking1_task.sdf
* [ ] practice_2022_acoustic_tracking2_task.sdf
* [ ] practice_2022_follow_path0_task.sdf
* [ ] practice_2022_follow_path1_task.sdf
* [ ] practice_2022_follow_path2_task.sdf
* [ ] practice_2022_perception0_task.sdf
* [ ] practice_2022_perception1_task.sdf
* [ ] practice_2022_perception2_task.sdf
* [ ] practice_2022_scan_dock_deliver0_task.sdf
* [ ] practice_2022_scan_dock_deliver1_task.sdf
* [ ] practice_2022_scan_dock_deliver2_task.sdf
* [ ] practice_2022_stationkeeping0_task.sdf
* [ ] practice_2022_stationkeeping1_task.sdf
* [ ] practice_2022_stationkeeping2_task.sdf
* [ ] practice_2022_wayfinding0_task.sdf
* [ ] practice_2022_wayfinding1_task.sdf
* [ ] practice_2022_wayfinding2_task.sdf
* [ ] practice_2022_wildlife0_task.sdf
* [ ] practice_2022_wildlife1_task.sdf
* [ ] practice_2022_wildlife2_task.sdf

**Review by M1chaelM — APPROVED** [review]
Looks good! Thanks!

**Comment by M1chaelM** [comment]
> Looks good! Thanks!

Oops, just noticed a small detail. To avoid confusion I'd like to remove the `<wind><linear_velocity>` element since we aren't using it anymore and it contrasts with the settings in the plugin we are using.

**Review by M1chaelM — APPROVED** [review]
OK, you may want to double check my last change but I think this should be good to go. Thanks!

**Comment by j-herman** [comment]
Ah, that's where those values were!  I forgot to go back to find them.  Looks good.

**Pull request merged**
