### PR TITLE
[Garden] Port Placard plugin

### PR DESCRIPTION
**Pull request by iche033**
Signed-off-by: Ian Chen <ichen@openrobotics.org>

Ported the `PlacardPlugin` from `master` branch. I added a `scan_dock_deliver_task.sdf` world for testing. Note that this is not the full task world as it's still missing other models and plugins like light buoy plugin and scan docker deliver scoring plugin. The new world just has the 2022 dock and placard models for testing.

To test:

1. launch the `scan_dock_deliver_task` world
  ```
  ros2 launch vrx_gz competition.launch.py world:=scan_dock_deliver_task
  ```

1. try shuffling the placards, e.g.

  ```sh
  gz topic -e -t /vrx/dock_2022_placard1/shuffle -m gz.msgs.Empty -p "unused: true"
  gz topic -e -t /vrx/dock_2022_placard2/shuffle -m gz.msgs.Empty -p "unused: true"
  gz topic -e -t /vrx/dock_2022_placard3/shuffle -m gz.msgs.Empty -p "unused: true"
  ```

1. try changing the symbol directly, e.g.

  ```sh
  gz topic -e -t /vrx/dock_2022_placard1/symbol -m gz.msgs.StringMsg_V -p "data: ['triangle', 'red']"
  gz topic -e -t /vrx/dock_2022_placard2/symbol -m gz.msgs.StringMsg_V -p "data: ['cross', 'green']"
  gz topic -e -t /vrx/dock_2022_placard3/symbol -m gz.msgs.StringMsg_V -p "data: ['rectangle', 'yellow']"
  ```

vrx_placard_plugin

### CODE REVIEW

**Review by caguero — COMMENTED** [review]
I made some tweaks in [d9b5baa](https://github.com/osrf/vrx/pull/532/commits/d9b5baaa4bad258896b42e832fd07a539b19e1bd).

**Comment by M1chaelM** [comment]
After building this morning I'm getting:
```
[ERROR] [launch]: Caught exception in launch (see debug for traceback): Caught exception when trying to load file of format [py]: No module named 'sdformat13'
```
Am I missing a dependency?

**Comment by caguero** [comment]
> 

This looks more like an issue with an SDF Python wrapper. If you compile Gazebo from source you need to set your `PYTHONPATH` environment variable to `<YOUR_GAZEBO_WS>/install/lib/python`

**Comment by M1chaelM** [comment]
Thanks! You were right--this fixed the problem:
```
export PYTHONPATH=$HOME/gazebo_ws/install/lib/python:$PYTHONPATH
```

**Review by M1chaelM — APPROVED** [review]
All working as expected. Thanks!

**Pull request merged**
