### PR TITLE
Fixed pinger bearing

### PR DESCRIPTION
**Pull request by andrew-aj**
Fixed issue #426

### CODE REVIEW

**Review by acxz — APPROVED** [review]

**Comment by M1chaelM** [comment]
@j-herman @caguero Following the discussion in #426, it looks like we decided not to make this change and instead document the convention we're using [here](https://github.com/osrf/vrx/wiki/frame_conventions#acoustic-pinger), so I'm closing this PR. Please re-open if I've misunderstood.

**Comment by acxz** [comment]
@M1chaelM can you just quickly update the wiki with the change?

**Comment by j-herman** [comment]
> @M1chaelM can you just quickly update the wiki with the change?

I added some clarification to the wiki - please let me know if it's not clear.  
New text reads:
"Bearings are reported in the WAM-V frame and coordinate system: the x-axis is towards the vehicle’s nose, the y-axis is towards the port side, and the z-axis points upwards. Following the right-hand rule, bearing angles are measured counter-clockwise beginning from the x-axis. "

**Comment by acxz** [comment]
This is wonderful! Thank you so much @j-herman! :love_you_gesture:

**Pull request closed without merging**
