### PR TITLE
Fix pinger location in gymkhana task 

### PR DESCRIPTION
**Pull request by caguero**
See issue #437. 

How to test it?

* Launch any of the `2022_practice` gymkhana worlds **(change the path to the world accordingly)**:

```
roslaunch vrx_gazebo gymkhana.launch verbose:=true world:=/home/caguero/vrx2022_ws/src/vrx/vrx_gazebo/worlds/2022_practice/gymkhana0.world
```

* Echo the set_pinger_position topic. Open a new terminal and run:

```
rostopic echo /wamv/sensors/pingers/pinger/set_pinger_position
```

You should observe that the pinger location is set to something different than the content of the `pinger.yaml` (-483, 295.5, 0).

* You can also teleoperate the robot to that location and echo the acoustic pinger:

```
/wamv/sensors/pingers/pinger/range_bearing
```

Verify that the range is close to `0`.

### CODE REVIEW

**Review by j-herman — APPROVED** [review]
All looks good!

**Comment by j-herman** [comment]
@caguero When I tried starting via `roslaunch vrx_gazebo vrx.launch world:=gymkhana0.world` the pinger position is not being published - the pinger position stays at the origin.  From your comments I think this is not the expected behavior when the gymkhana scoring plugin is running.  Do you want me to take a look to see what's up, or did I misunderstand what's supposed to happen?

**Comment by caguero** [comment]
> roslaunch vrx_gazebo vrx.launch world:=gymkhana0.world

Hmm, I see the position being published. Is `gymkhana0.world` the one under `2022_practice`?

**Comment by j-herman** [comment]
Never mind - dumb mistake on my part!  I am fixing it now and will confirm it's working.

**Comment by j-herman** [comment]
It's working now.  Good to merge.

**Pull request merged**
