### PR TITLE
Improve Sydney Regatta performance

### PR DESCRIPTION
**Pull request by caguero**
See issue #367.

This pull request adds a new simplified mesh for the Sydney Regatta world to be used for collision checking. I can see better CPU usage in my machine and it's running in real-time.

Maybe @bsb808 or @M1chaelM  can test it on the cloud to check if the speedup is more evident.

@JonathanWheare, feel free to give it a shot.

### CODE REVIEW

**Comment by caguero** [comment]
> @caguero I'm still seeing a RTF of 0.65 in the cloud using this collision model. This is better than the 0.4 Brian was seeing, though. When I totally disable the collision for the Sydney Regatta model, RTF bumps up to 1.0, though FPS is still around 2.3. If I also delete the visual model, I go up to RTF 1.0 and FPS 6-7, so it does seem that this model is having a big impact.
> 
> Should I test anything else? I think this is a step in the right direction. Not sure if there is more to change before we merge.

Thanks for testing in the cloud. Let me see if we can improve things before merging.

**Comment by caguero** [comment]
> > @M1chaelM , I updated the mesh. Do you mind to give it a shot again in the cloud to see where we are?
> 
> It seems to have gotten a bit worse for some reason. I'm seeing RTF 0.59 and FPS 3.23.

Thanks, let me keep looking into it...

**Comment by M1chaelM** [comment]
> Can you confirm it on your end?
We are waiting on a fix for cloudsim. We've been unable to launch new machines to test this for a couple of days (apparently due to a shortage of EC2 instances!?). I will test as soon as we can get something to try it on.

**Comment by M1chaelM** [comment]
@caguero I was able to test this today and I'm now getting a RTF between 0.91-0.95, so much better. The frame rate is still extremely low at around 2.75. This varies depending on what's in the scene, but it's never higher than 9. Deleting the arena height map raises FPS to around 9 also.

**Comment by caguero** [comment]
> @caguero I was able to test this today and I'm now getting a RTF between 0.91-0.95, so much better. The frame rate is still extremely low at around 2.75. This varies depending on what's in the scene, but it's never higher than 9. Deleting the arena height map raises FPS to around 9 also.

Great! About the FPS, did you try disabling the tree visuals?

**Comment by M1chaelM** [comment]
> Great! About the FPS, did you try disabling the tree visuals?

Surprisingly, this seems to improve both the RTF and FPS a little bit. RTF goes to 0.95-0.96 and FPS goes to 3.1-3.3.

**Comment by JonathanWheare** [comment]
Using this version, I am seeing a real time factor of around 0.97 to 0.98 with 120% CPU on my laptop.  Reverting to the current master branch, I am getting about 0.6 RTF with 160-180%CPU.  Seems like a significant improvement.

**Comment by caguero** [comment]
I feel this change is good enough for this pull request. How about we stop here and try to tackle the rendering performance issue in a separate patch?

**Review by M1chaelM — APPROVED** [review]
I agree the improvement is good enough to warrant merging this PR.

**Pull request merged**
