### PR TITLE
adding 2022 elements to vrx.launch

### PR DESCRIPTION
**Pull request by M1chaelM**
This resolves issue #279

To test, run:
```
roslaunch vrx_gazebo vrx.launch
```
You should see the light buoy, docks, gymkhana course and our 3 animals:

vrx_2022_launch

### CODE REVIEW

**Comment by bsb808** [comment]
I think we need to first address PRs #354 and #358  - then when those are merged, rebase this branch to see if it still works as expected.  I suspect that the model poses will need to be modified.

**Comment by M1chaelM** [comment]
> I think we need to first address PRs #354 and #358 - then when those are merged, rebase this branch to see if it still works as expected. I suspect that the model poses will need to be modified.

@bsb808  Sure, I can take a look at those now. That said, I have already created this file and it appears to be working, so I think it would be safe to go ahead and approve. If changes are needed I will add them as part of the PR that introduces the need for new poses. Is there any downside to this?

**Comment by bsb808** [comment]
> > I think we need to first address PRs #354 and #358 - then when those are merged, rebase this branch to see if it still works as expected. I suspect that the model poses will need to be modified.
> 
> @bsb808 Sure, I can take a look at those now. That said, I have already created this file and it appears to be working, so I think it would be safe to go ahead and approve. If changes are needed I will add them as part of the PR that introduces the need for new poses. Is there any downside to this?

Just seems like a little more work to test this modification twice, once now and then again after we fix the coordinates.

**Review by bsb808 — APPROVED** [review]
Good to go for 1.5

**Pull request merged**
