### PR TITLE
Add utility script for rapidly shutting down gazebo

### PR DESCRIPTION
**Pull request by bsb808**
This is a hack I use to be quickly shutdown the sim...

```
rosrun vrx_gazebo killgazebo.sh
```

Is there a better way?

### CODE REVIEW

**Comment by caguero** [comment]
Isn't the usual `CTRL-C` working for you? 90% of the time works for me and when it doesn't I manually run the `kill` command for the server.

**Review by caguero — COMMENTED** [review]
Not sure if it's strictly necessary but maybe we need this line in the `CMakeLists.txt`:

```
install(PROGRAMS scripts/kill_gazebo.sh
  DESTINATION ${CATKIN_PACKAGE_BIN_DESTINATION})
```

You could probably move it to the `scripts` directory as well.

**Comment by bsb808** [comment]
The script is just a convenience.  It shuts down gazebo (client and server) much faster than the ctrl-c interrupt.

**Comment by bsb808** [comment]
> Not sure if it's strictly necessary but maybe we need this line in the `CMakeLists.txt`:
> 
> ```
> install(PROGRAMS scripts/kill_gazebo.sh
>   DESTINATION ${CATKIN_PACKAGE_BIN_DESTINATION})
> ```
> 
> You could probably move it to the `scripts` directory as well.

ROS seems to find the executable in any subdirectly of the package.  For me, this works....
rosrun vrx_gazebo killgazebo.sh

**Review by caguero — APPROVED** [review]

**Pull request merged**
