### PR TITLE
Wayfinding practice worlds

### PR DESCRIPTION
**Pull request by caguero**
Similar to #582 but for the wayfinding practice worlds.

How to test it?

Follow instructions from #582 but launch the worlds with:
```
ros2 launch vrx_gz competition.launch.py world:=practice_2022_wayfinding0_task
ros2 launch vrx_gz competition.launch.py world:=practice_2022_wayfinding1_task
ros2 launch vrx_gz competition.launch.py world:=practice_2022_wayfinding2_task
```

### CODE REVIEW

**Comment by caguero** [comment]
@M1chaelM , the environmental conditions have been updated. This PR is ready for review.

**Comment by M1chaelM** [comment]
@caguero It looks like the waypoint markers aren't enabled. To you want to merge #582 first?

**Comment by M1chaelM** [comment]
@caguero Looks like we are using exactly the same waypoints for worlds 0 and 2. I'm guessing this is a copy error?

**Review by M1chaelM — CHANGES_REQUESTED** [review]
Looks almost ready to go--can we use different waypoints for practice worlds 0 and 2?

**Comment by caguero** [comment]
> @caguero Looks like we are using exactly the same waypoints for worlds 0 and 2. I'm guessing this is a copy error?

Good catch, I just updated the waypoints of world 2.

**Pull request merged**
