### PR TITLE
Update example_component_config.yaml and numeric.yaml for generating compliant WAM-V URDFs

### PR DESCRIPTION
**Pull request by Tinker-Twins**
### The current `example_component_config.yaml` lacks two things:

**1. Functional aspect:** It does not include the `wamv_pinger` component! If a custom WAM-V URDF is generated without this component, it still passes the compliance checks, but the sensor is not instantiated. When the Gymkhana task is launched, no data is published to `/wamv/sensors/pingers/pinger/range_bearing` topic. Consequently, it is impossible to localize the black box, and hence complete the task.

**2. Readability:** The example config sets a standard in front of developers, and hence it is common to assume that it is self-contained to its fullest abilities. However, the current version does not include all the allowable parameters for most of the components.

### The current `numeric.yaml` lacks two things:

**1. Functional aspect:** `wamv_gps` and `wamv_imu` do nat have the parameter `post_Y`.

**2. Readability:** Sequence of the components does not match that in the `example_component_config.yaml` file.

### Changes:

The said files have been updated to address the concerns raised above. Particularly, the `example_component_config.yaml` file now contains defination for `wamv_pinger` component, and includes all the allowable parameters for all the components. The `numeric.yaml` file is rearranged to match component sequence as in the `example_component_config.yaml` file, and unnecessary parameters have been removed.

### CODE REVIEW

**Comment by M1chaelM** [comment]
@caguero Note that our example team at https://github.com/osrf/vrx-docker/tree/master/team_config/example_team is also missing a pinger, so we may way to update that also.

**Review by caguero — APPROVED** [review]
All looks good to me! Thanks for the contribution! Just one more minor request. As @M1chaelM  pointed out, could you add the pinger to the components file of our team example?

https://github.com/osrf/vrx-docker/tree/master/team_config/example_team

**Comment by Tinker-Twins** [comment]
Sure, no problem!

**Comment by Tinker-Twins** [comment]
Created https://github.com/osrf/vrx-docker/pull/51 by adding the pinger component to the [`component_config.yaml`](https://github.com/osrf/vrx-docker/blob/master/team_config/example_team/component_config.yaml).

Besides this, we found that there were a few inconsistencies between the [`component_config.yaml`](https://github.com/osrf/vrx-docker/blob/master/team_config/example_team/component_config.yaml) and [`thruster_config.yaml`](https://github.com/osrf/vrx-docker/blob/master/team_config/example_team/thruster_config.yaml) of the [`vrx-docker`](https://github.com/osrf/vrx-docker/tree/master/team_config/example_team) repository as compared with [`example_component_config.yaml`](https://github.com/osrf/vrx/blob/master/vrx_gazebo/config/wamv_config/example_component_config.yaml) and [`example_thruster_config.yaml`](https://github.com/osrf/vrx/blob/master/vrx_gazebo/config/wamv_config/example_thruster_config.yaml) of the [`vrx`](https://github.com/osrf/vrx/tree/master/vrx_gazebo/config/wamv_config) repository, and have resolved them as well.

**Comment by M1chaelM** [comment]
Thanks for this contribution. Since this is approved I'm going to go ahead and merge.

**Comment by Tinker-Twins** [comment]
@M1chaelM, PR https://github.com/osrf/vrx-docker/pull/51 is still pending. Kindly review and merge it so that there wouldn't be any inconsistency between the two repositories.

**Pull request merged**
