### PR TITLE
Support kinetic melodic and  noetic

### PR DESCRIPTION
**Pull request by rolker**
An alternative to creating a noetic branch (#237 ) to solve #230  is to check in the CMakeLists.txt files for the ROS distribution to determine the need for INLINE.

### CODE REVIEW

**Review by d130s — APPROVED** [review]
Thanks for taking over #230 with commits being preserved!

**Comment by rolker** [comment]
No problem @d130s , wanted to make sure you got credit for your part.

Unfortunately, my fix doesn't seem to have passed CI on kinetic and I don't have a kinetic setup to test and debug, so I'm hoping someone out there might be able to help?

**Comment by mabelzhang** [comment]
The Kinetic failure looks like an error on the new addition on the `INLINE`. I think it's a typo that's supposed to say `INORDER`?

**Comment by rolker** [comment]
Oh yes! That makes sense @mabelzhang. I'll push a fix and see if it passes CI.

**Comment by mabelzhang** [comment]
FYI this repo is currently "maintained" and not in active development, so response time can be slow.
This one looks quick enough. If it's something involved, I can't guarantee we'll be testing and merging PRs right now, just so you know.

**Comment by rolker** [comment]
Thanks for the heads up regarding maintenance status. 

I'm using the WAM-V model as well as the Cora model from VORC as guides to building a gazebo simulation of our own USV.

Our model does use the usv_gazebo_plugins package and according to http://wiki.ros.org/usv_gazebo_plugins, this seems to be where I should contribute PRs and such.

I'll be working from my own fork anyway so I don't mind if PRs here sit around for a while. Should I keep sending some anyway? I don't expect many since the innards of the plugins probably won't be where I'm focusing my efforts.

**Comment by mabelzhang** [comment]
Glad it's of help to you!

Of course, feel free to send PRs, it could help others even if we aren't getting around to them. Thank you!

**Review by mabelzhang — APPROVED** [review]
CI is passing. Thank you for the fix to enable all three distros!
We haven't run on Noetic, but since this works for you both, I'll merge it. We don't have CI set up for Noetic at the moment, so I'd say Noetic is community-supported right now.

**Pull request merged**
