### PR TITLE
Follow-the-path task

### PR DESCRIPTION
**Pull request by caguero**
The follow the path task including:

* Example world
* Practice worlds
* We can reuse the navigation scoring plugin

How to test it?

1. Launch the simulation:
```
ros2 launch vrx_gz competition.launch.py world:=follow_path_task
```

2. Launch the joystick teleoperation node:
```
ros2 launch vrx_gz usv_joy_teleop.py
```

3. Teleoperate the robot through the course. The task should successfully finish after crossing the last gate. Crossing the gates in the wrong error should also trigger the task to finish (unsuccessfully).

### CODE REVIEW

**Comment by M1chaelM** [comment]
I'm getting expected behavior from `follow_path_task` and `practice_2022_follow_path0_task`, which both use the same `short_navigation_course_0`. When I try to run `practice_2022_follow_path1_task` and `practice_2022_follow_path2_task`, I don't get any notification when I pass through gates and I'm unable to complete the task.

**Review by M1chaelM — CHANGES_REQUESTED** [review]
This looks like it's working but I think we should add more gates for runs 1 and 2. The reason is that we're reverting to a task more like the one we had in VRX 2019, which specified 2-10 gates, rather than the 2-5 for the gymkhana navigation channel. To set expectations correctly, I think it would be good to have 3, 6, and 9-10 gates for practice worlds 0, 1, and 2, respectively.

Also, in world 2 I notice the buoys in the second gate are very far apart. This may be fine if they are within 25 meters, but I thought it might be worth double checking.

**Comment by caguero** [comment]
> This looks like it's working but I think we should add more gates for runs 1 and 2. The reason is that we're reverting to a task more like the one we had in VRX 2019, which specified 2-10 gates, rather than the 2-5 for the gymkhana navigation channel. To set expectations correctly, I think it would be good to have 3, 6, and 9-10 gates for practice worlds 0, 1, and 2, respectively.
> 
> Also, in world 2 I notice the buoys in the second gate are very far apart. This may be fine if they are within 25 meters, but I thought it might be worth double checking.

All right, I just modified the navigation courses to have `3, `6` and `9` gates. I also added extra obstacles.

**Comment by M1chaelM** [comment]
Courses 1 and 2 don't score past the third gate. I think because the scoring plugin initialization hasn't been updated to reflect the new models.

**Comment by M1chaelM** [comment]
OK, I added those gates and it looks like it's working now.

**Review by M1chaelM — APPROVED** [review]

**Comment by caguero** [comment]
> OK, I added those gates and it looks like it's working now.

Thanks!

**Pull request merged**
