### PR TITLE
Loading WAM-V

### PR DESCRIPTION
**Pull request by caguero**
This pull request makes it possible to load a WAM-V without sensors. A base WAM-V without plugins has been uploaded to Fuel ([see the VRX collection](https://app.gazebosim.org/OpenRobotics/fuel/collections/vrx)). A `wamv/model.sdf.erb` has been created in this repository containing the necessary plugins and future configurations.

How to test it?

Run the world:
```
ros2 launch vrx_ros competition_local.launch.py ign_args:="-v 4 -r sydney_regatta.sdf"
```

Load the WAM-V:
```
ros2 launch vrx_ign spawn.launch.py name:=wamv world:=sydney_regatta model:=wam-v x:=-532 y:=162 z:=0.1 R:=0 P:=0 Y:=1
```

You can try sending thruster commands with:
```
ign topic -t /model/wamv/joint/left_engine_propeller_joint/cmd_thrust -m ignition.msgs.Double -p 'data: 50.0'
ign topic -t /wamv/left/thruster/joint/cmd_pos -m ignition.msgs.Double -p 'data: 1.0'
```
2022-07-25T23:42:07 113118857

Note: There's still some inconsistency in the topic names that I'll fix in a separate pull request.

### CODE REVIEW

**Comment by M1chaelM** [comment]
@caguero I'm confused by the wamv launch command:
```
ros2 launch mbzirc_ros competition_local.launch.py ign_args:="-v 4 -r simple_demo.sdf"
```
Do I need to have mbzirc built, or is this a typo?

**Comment by caguero** [comment]
> @caguero I'm confused by the wamv launch command:
> 
> ```
> ros2 launch mbzirc_ros competition_local.launch.py ign_args:="-v 4 -r simple_demo.sdf"
> ```
> 
> Do I need to have mbzirc built, or is this a typo?

Sorry, this is a typo, for some reason I copied the previous command. I updated the instructions.

**Comment by M1chaelM** [comment]
Everything seems to work, but when I spawn the vehicle I see the stack trace below in the output. Seems to be looking for a `video_target_relay`. Can this be ignored? If so I'm ready to approve.

```
Task exception was never retrieved
future: <Task finished name='Task-16' coro=<LaunchService._process_one_event() done, defined at /opt/ros/galactic/lib/python3.8/site-packages/launch/launch_service.py:226> exception=SubstitutionFailure("executable 'video_target_relay' not found on the libexec directory '/home/username/vrx_ign/install/lib/vrx_ros' ")>
Traceback (most recent call last):
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/launch_service.py", line 228, in _process_one_event
    await self.__process_event(next_event)
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/launch_service.py", line 248, in __process_event
    visit_all_entities_and_collect_futures(entity, self.__context))
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures
    futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 38, in visit_all_entities_and_collect_futures
    sub_entities = entity.visit(context)
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/action.py", line 108, in visit
    return self.execute(context)
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch_ros/actions/node.py", line 484, in execute
    ret = super().execute(context)
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/actions/execute_process.py", line 837, in execute
    self.__expand_substitutions(context)
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/actions/execute_process.py", line 681, in __expand_substitutions
    cmd = [perform_substitutions(context, x) for x in self.__cmd]
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/actions/execute_process.py", line 681, in <listcomp>
    cmd = [perform_substitutions(context, x) for x in self.__cmd]
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/utilities/perform_substitutions_impl.py", line 26, in perform_substitutions
    return ''.join([context.perform_substitution(sub) for sub in subs])
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/utilities/perform_substitutions_impl.py", line 26, in <listcomp>
    return ''.join([context.perform_substitution(sub) for sub in subs])
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/launch_context.py", line 197, in perform_substitution
    return substitution.perform(self)
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch_ros/substitutions/executable_in_package.py", line 84, in perform
    raise SubstitutionFailure(
launch.substitutions.substitution_failure.SubstitutionFailure: executable 'video_target_relay' not found on the libexec directory '/home/username/vrx_ign/install/lib/vrx_ros'
```

**Comment by caguero** [comment]
> 5497301

I just removed it in [5497301](https://github.com/osrf/vrx/pull/490/commits/54973016ae7787737a7cdb76ad270aedf9de9d16). It shouldn't be happening now.

**Review by M1chaelM — APPROVED** [review]
That worked. All looking good!

**Pull request merged**
