### PR TITLE
Update CI Images and Restore buoy generator

### PR DESCRIPTION
**Pull request by M1chaelM**
This addresses issue #242 and also fixes the names of 3 Python scripts that were missing the `.py` extension.

### CODE REVIEW

**Comment by M1chaelM** [comment]
Tests on the older OS are currently failing as expected because we've added Python 3 as a dependency but have not updated these images. We should fix these images before merging.

**Comment by M1chaelM** [comment]
The main focus of this PR has now shifted from restoring a nonessential Python script to updating the CI images for the whole repository. 
* I have set up a separate repository for the Dockerfiles for these baseline images at [Field-Robotics-Lab/dockwater](https://github.com/Field-Robotics-Lab/dockwater) on Github. 
* I also created a Dockerhub repository to host the built images at [npslearninglab/watery_robots](https://hub.docker.com/r/npslearninglab/watery_robots).
Merging this PR will update the github action workflow to check against the images in the repository instead of the ones we previously used.

**Comment by M1chaelM** [comment]
@caguero I think this is ready for review when you have a moment. Thanks!

**Review by caguero — APPROVED** [review]
Looks good to me!

**Pull request merged**
